title: Community Members
description: An interactive map of our community members.
github_project: smortex/map
baseurl: "/map" # the subpath of your site, e.g. /map
url: "https://smortex.github.io" # the base hostname & protocol for your site, e.g. https://example.com
thunderforest_apikey: "f001bec5e17447b0b597e5a8e766bbf2" # the Thunderforest API key for map tiles
min_users_for_local_map: 5 # With that many users or more, bound the map to them, otherwise display the whole earth

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
