---
name: Add me to the map
run-name: 'Add ${{ github.triggering_actor }} to the map'

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Location / Address (read from user profile when empty)'
        required: false
        type: string
      latitude:
        description: 'Override latitude (-90.0 to 90.0)'
        required: false
        type: number
      longitude:
        description: 'Override longitude (-180.0 to 180.0)'
        required: false
        type: number

permissions:
  contents: write

jobs:
  add_me_to_the_map:
    name: 'Add me to the map'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add user location
        run: |
          ./.github/actions/add-user-location ${{ github.triggering_actor }}
        env:
          INPUT_LATITUDE: ${{ github.event.inputs.latitude }}
          INPUT_LONGITUDE: ${{ github.event.inputs.longitude }}
          INPUT_LOCATION: ${{ github.event.inputs.location }}
          GEOAPIFY_KEY: ${{ secrets.GEOAPIFY_KEY }}
      - name: Aggregate all users locations
        uses: ./.github/actions/aggregate-members-location
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add ${{ github.triggering_actor }} to the map"
