---
name: Remove me from the map
run-name: 'Remove ${{ github.triggering_actor }} from the map'

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  remove_me_from_the_map:
    name: 'Remove me from the map'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Remove user location
        run: |
         rm -f _data/${{ github.triggering_actor }}.json
      - name: Aggregate all users locations
        uses: ./.github/actions/aggregate-members-location
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Remove ${{ github.triggering_actor }} from the map"
